spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service
      auto-offset-reset: latest

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings