server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/inventorydb
    username: inventory
    password: inventory

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
    show-sql: false

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service
      auto-offset-reset: latest

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,env
  endpoint:
    env:
      show-values: ALWAYS