version: "3.9"

services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_INTERNAL://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  booking-db:
    image: postgres:16
    container_name: booking-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: bookingdb
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
    volumes:
      - booking-db-data:/var/lib/postgresql/data

  inventory-db:
    image: postgres:16
    container_name: inventory-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory
    volumes:
      - inventory-db-data:/var/lib/postgresql/data

  payment-db:
    image: postgres:16
    container_name: payment-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment
    volumes:
      - payment-db-data:/var/lib/postgresql/data

  loyalty-db:
    image: postgres:16
    container_name: loyalty-db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: loyaltydb
      POSTGRES_USER: loyalty
      POSTGRES_PASSWORD: loyalty
    volumes:
      - loyalty-db-data:/var/lib/postgresql/data

  baggage-db:
    image: postgres:16
    container_name: baggage-db
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: baggagedb
      POSTGRES_USER: baggage
      POSTGRES_PASSWORD: baggage
    volumes:
      - baggage-db-data:/var/lib/postgresql/data

volumes:
  booking-db-data:
  inventory-db-data:
  payment-db-data:
  loyalty-db-data:
  baggage-db-data:
