spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bookingdb
    username: booking
    password: booking
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true

kafka:
  bootstrap-servers: localhost:9092

loyalty:
  soap:
    endpoint: http://localhost:8084/ws
    connect-timeout: 5000
    read-timeout: 10000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
